### ISSUE TITLE
Support for more than one server

### ISSUE THREAD

**Issue by Darthyoda714** [sjstein/R8DIUM#105]
The ability for the bot to be able to handle multiple host security files on the same computer for servers hosting multiple R8 regions on the same hosting machine.

**Comment by sjstein** [comment]
Assumptions:

1. The user database is the same for all servers
2. The instantiation of the different servers is done via unique directory structures (but on the same machine)
3. There will never be a case where a user is banned on only one region

**Comment by sjstein** [comment]
First iteration is just to have the option to write to multiple HostSecurity files when the time comes to update them.

In terms of merging the HostSecurity data back in to the user db, it is *probably* safe to just use one, as right now we are really only grabbing the UID.

**Comment by sjstein** [comment]
For the logging/pruning of users, rather than a log of each "last login", it would be simpler on the schema to add not only the "last_login" field, but also "last_server" field.

Envisioning the configuration file having entries as such:

[server1]
name = CaliSW
security_file = C:\Program Files\Run8Studios\CaliServer\Run8 Train Simulator V3\...etc.
log_file =  C:\Program Files\Run8Studios\CaliServer\Run8 Train Simulator V3\...etc.

[server2]
name = SouthEast
security_file = C:\Program Files\Run8Studios\SeServer\Run8 Train Simulator V3\...etc.
log_file =  C:\Program Files\Run8Studios\SeServer\Run8 Train Simulator V3\...etc.

**Comment by sjstein** [comment]
This is currently being tested on branch #105

**Comment by sjstein** [comment]
This has been addressed in branch #108
